// Array To Contains All Product
let productsMen = [
  {
    id: 0,
    numOfProduct: 0,
    title: "Classic Spring",
    imageUrl: "images/men-01.jpg",
    price: 120,
    arrayName: "productsMen",
    qty: 1,
    isMe: "N",
  },
  {
    id: 1,
    numOfProduct: 1,
    title: "Air Force 1X",
    imageUrl: "images/men-02.jpg",
    price: 90,
    arrayName: "productsMen",
    qty: 1,
    isMe: "N",
  },
  {
    id: 2,
    numOfProduct: 2,
    title: "Love Nana ‘20",
    imageUrl: "images/men-03.jpg",
    price: 150,
    arrayName: "productsMen",
    qty: 1,
    isMe: "N",
  },
  {
    id: 3,
    numOfProduct: 3,
    title: "Classic clothes",
    imageUrl: "images/men-01.jpg",
    price: 120,
    arrayName: "productsMen",
    qty: 1,
    isMe: "N",
  },
  {
    id: 4,
    numOfProduct: 4,
    title: "Air Force 2X",
    imageUrl: "images/men-02.jpg",
    price: 90,
    arrayName: "productsMen",
    qty: 1,
    isMe: "N",
  },
];

let productsWomen = [
  {
    id: 0,
    numOfProduct: 5,
    title: "New Green Jacket",
    imageUrl: "images/women-01.jpg",
    price: 110,
    arrayName: "productsWomen",
    qty: 1,
    isMe: "N",
  },
  {
    id: 1,
    numOfProduct: 6,
    title: "Classic Dress",
    imageUrl: "images/women-02.jpg",
    price: 180,
    arrayName: "productsWomen",
    qty: 1,
    isMe: "N",
  },
  {
    id: 2,
    numOfProduct: 7,
    title: "Spring Collection",
    imageUrl: "images/women-03.jpg",
    price: 120,
    arrayName: "productsWomen",
    qty: 1,
    isMe: "N",
  },
  {
    id: 3,
    numOfProduct: 8,
    title: "Classic Spring",
    imageUrl: "images/women-01.jpg",
    price: 75,
    arrayName: "productsWomen",
    qty: 1,
    isMe: "N",
  },
  {
    id: 4,
    numOfProduct: 9,
    title: "New Green Jacket 2X",
    imageUrl: "images/women-02.jpg",
    price: 130,
    arrayName: "productsWomen",
    qty: 1,
    isMe: "N",
  },
];

let productsKids = [
  {
    id: 0,
    numOfProduct: 10,
    title: "School Collection",
    imageUrl: "images/kid-01.jpg",
    price: 105,
    arrayName: "productKids",
    qty: 1,
    isMe: "N",
  },
  {
    id: 1,
    numOfProduct: 11,
    title: "Summer Cap",
    imageUrl: "images/kid-02.jpg",
    price: 100,
    arrayName: "productKids",
    qty: 1,
    isMe: "N",
  },
  {
    id: 2,
    numOfProduct: 12,
    title: "Classic Kid",
    imageUrl: "images/kid-03.jpg",
    price: 50,
    arrayName: "productKids",
    qty: 1,
    isMe: "N",
  },
  {
    id: 3,
    numOfProduct: 13,
    title: "Classic Clothes",
    imageUrl: "images/kid-01.jpg",
    price: 70,
    arrayName: "productKids",
    qty: 1,
    isMe: "N",
  },
  {
    id: 4,
    numOfProduct: 14,
    title: "School Collection X2",
    imageUrl: "images/kid-03.jpg",
    price: 90,
    arrayName: "productKids",
    qty: 1,
    isMe: "N",
  },
];

let allProduct = productsMen.concat(productsWomen, productsKids);
